### ISSUE TITLE
Fix the login session expiring in a few minutes 

### ISSUE THREAD

**Issue by CodeWithTheDoctor** [codersforcauses/coexist#112]
## Basic Information
- After 5-10 minutes or so of being on the site, the upcoming events don't load and requests ive 401 (unauthorised) even though the user is signed in on the frontend. 
- I suspect the user's session has experied on the backend. 

Ideas to fix:
- eliminate the session expiry on backend, or
- Sign user out on frontend when session has expired rather than current unexpected behaviour

**Comment by dct0** [comment]
The token should be refreshed when the old one expires in the axios interceptor on the FE

**Comment by CodeWithTheDoctor** [comment]
Oh ok. Also I forgot to mention, this is occuring on i57 branch, maybe it
doesn't have latest main changes which might have a fix (oops :P)

**Comment by K-Straiton** [comment]
> Oh ok. Also I forgot to mention, this is occuring on i57 branch, maybe it doesn't have latest main changes which might have a fix (oops :P)

Can confirm it still occurs in up to date branches
