### ISSUE TITLE
No Module named 'django'

### ISSUE THREAD

**Issue by SureshPradhana** [codersforcauses/coexist#15]
## Basic Information

I tried to open this project on my local machine following the README development guide. Here are the steps I took:

1. Moved `.env.example` into `.env` of the client and server folders respectively.
2. Ran `docker-compose up -d` to start the database.
3. Changed directory to the server: `cd server`.
4. Ran `poetry install`.
5. Attempted to run `python manage.py migrate`, but encountered the following error:

```
python manage.py migrate
Traceback (most recent call last):
  File "/home/suresh/projects/coexist/server/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/suresh/projects/coexist/server/manage.py", line 22, in <module>
    main()
  File "/home/suresh/projects/coexist/server/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

## Other Information

In an attempt to resolve the issue, I created a virtual environment for the server:

1. Created a virtual environment: `python -m venv venv`.
2. Activated the virtual environment: `source venv/bin/activate`.
3. Ran `python manage.py migrate`, which now throws a different error:

```
Traceback (most recent call last):
  File "/home/suresh/projects/coexist/server/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
```

I want to know what I am doing wrong.

**Comment by dct0** [comment]
This repo only work in a dev container. Alternatively you need to activate the env created by poetry
