### ISSUE TITLE
Connect login modal to the backend

### ISSUE THREAD

**Issue by dct0** [codersforcauses/coexist#45]
## Basic Information
BRANCH OFF #12 IF NOT MERGED ALREADY

Create a `useAuth` hook in the `client/src/hooks/auth.ts`. It should contain a method `login()` which when called
- Calls the jwt endpoint with the username and password, this will return a token if it's a valid user
- Store the token in cookies, which will expire after x time (up to your discretion)
- Attach the token to all backend requests with an axios interceptor https://www.thedutchlab.com/en/insights/using-axios-interceptors-for-refreshing-your-api-token . This currently lives in `client/src/lib/api.ts`
- Add an additonal condition: if the backend request fails, try refreshing the token with the corresponding endpoint. Take a look at https://github.com/codersforcauses/csf/blob/b92a97f1656e50b107151af863ee45b166431394/client/src/utils/server.ts#L22 for help (it's in vue but similar concept)

## Other Information
There's no need to use tanstack query for this, (unlike the usePings example). You can just create a vanilla hook

**Comment by SetroZ** [comment]
Why don't we set the cookie by the server as an **http-only** to avoid all the headache.? and have the refresh token updated **after:**

- old refresh token is sent to the server AND remaining days till expiry is < 10 days (for example)
- or whenever a request is sent

We could have the server set a dummy refresh token with the same expiry date which could be accessed by the client for the sake of determining the user state i.e ```Login: True | False``` and just have the hook read the cookie and set the login state or in a context
