### ISSUE TITLE
Create user endpoint

### ISSUE THREAD

**Issue by dct0** [codersforcauses/coexist#47]
## Basic Information
Create an endpoint at `/api/users/me` which:
- Returns the currently logged in user's information (omitting sensitive stuff obviously)
- Will 401 if the user is not logged in

## Other Information
**[Are there any additional information that we should know about?]**

**Comment by Connor2803** [comment]
Seems to be working well
![image](https://github.com/user-attachments/assets/1bcc780c-af9c-49b9-be45-cfa59239feae)
