### ISSUE TITLE
Create event api tests

### ISSUE THREAD

**Issue by dct0** [codersforcauses/coexist#59]
## Basic Information
Create tests for all the event api endpoints. Make sure to also test negative cases e.g. 400

## Other Information
**[Are there any additional information that we should know about?]**

**Comment by JoelRaju403** [comment]
Should we also include RSVP testcases as well?

**Comment by dct0** [comment]
> Should we also include RSVP testcases as well?

No that's okay for now because it requires auth to be merged in first
