### ISSUE TITLE
Update RSVP endpoint to create for current user

### ISSUE THREAD

**Issue by harryrigg** [codersforcauses/coexist#97]
## Basic Information
- Currently, the RSVP post endpoint requires the event_id and user_id be passed through request data.
- Instead, it should get the user_id from the currently authenticated user (request.user), and the event from the URL parameter (/<event_id>/rsvp).

**Comment by JoelRaju403** [comment]
Yeah might be something to do with the permissions that POST has in the RSVP views. Will look into it

**Comment by harryrigg** [comment]
> Yeah might be something to do with the permissions that POST has in the RSVP views. Will look into it

Think it's only part of issue. I changed the permission class from IsStaffOrReadonly to IsAuthenticated, and it doesn't give a 401 error anymore, but still not working.
